# Generated by Django 2.1.5 on 2019-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBBMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('attendee_pw', models.CharField(max_length=100, unique=True)),
                ('moderator_pw', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
