# Generated by Django 2.1.5 on 2019-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0002_auto_20190117_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbmeeting',
            name='allowStartStopRecording',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='bbbmeeting',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bbbmeeting',
            name='record',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='bbbmeeting',
            name='welcome',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
