# Generated by Django 2.1.5 on 2019-01-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0003_auto_20190117_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbmeeting',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
