# Generated by Django 2.1.5 on 2019-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0004_bbbmeeting_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbmeeting',
            name='create_url',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
