# Generated by Django 2.1.5 on 2019-01-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0005_bbbmeeting_create_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbbmeeting',
            name='create_url',
        ),
    ]
